### ISSUE TITLE
No connection to blockchain error

### ISSUE THREAD

**Issue by AnnyBuh** [DecentralCardGame/frontend#67] opened 2022-01-10 09:23 UTC
Can't connect to blockchain error (as per screenshot) with safari and microsoft edge browser. brave and chrome are working. I'm on a Mac. This error started yesterday in the evening between 21-22h German time, after I tried to search for a name in the gallery.

**Comment by AnnyBuh** [comment] 2022-01-10 09:23
<img width="525" alt="Bildschirmfoto 2022-01-10 um 11 20 28" src="https://user-images.githubusercontent.com/48418575/148743072-46ab4b87-4cdc-4418-bf99-5443103c460d.png">

**Comment by AnnyBuh** [comment] 2022-01-10 09:24
Oh actually it is now also happening on chrome and brave. it seems that the name search is the problem.

**Comment by patrickwieth** [comment] 2022-01-10 09:28
duplicate of #66

**Closed by patrickwieth** 2022-01-10 09:28 UTC
